import { StyleSheet } from 'react-native'
import { CARD_SHADOW, HEADER_PADDING_TOP } from '../constants/themes'
import { ResolvedColors } from '../types/theme'
import { withOpacity } from '../utils/colorUtils'

export const createEditScreenStyles = (colors: ResolvedColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.SECONDARY,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      paddingTop: HEADER_PADDING_TOP,
      backgroundColor: colors.PRIMARY,
    },
    backButton: {
      padding: 8,
    },
    deleteButton: {
      padding: 8,
    },
    title: {
      fontSize: 20,
      fontWeight: 'bold',
      color: colors.WHITE,
    },
    form: {
      padding: 20,
    },
    formGroup: {
      marginBottom: 20,
    },
    label: {
      fontSize: 16,
      fontWeight: 'bold',
      color: colors.BLACK,
      marginBottom: 8,
    },
    input: {
      backgroundColor: colors.WHITE,
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      ...CARD_SHADOW,
    },
    noteInput: {
      backgroundColor: colors.WHITE,
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      minHeight: 80,
      textAlignVertical: 'top',
      ...CARD_SHADOW,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: colors.BLACK,
      marginBottom: 12,
    },
    extraFieldsContainer: {
      backgroundColor: colors.WHITE,
      borderRadius: 8,
      padding: 12,
      ...CARD_SHADOW,
    },
    extraFieldRow: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 12,
    },
    extraFieldHalf: {
      flex: 1,
    },
    extraFieldFull: {
      marginBottom: 0,
    },
    extraFieldLabel: {
      fontSize: 13,
      color: colors.GRAY[600],
      marginBottom: 6,
    },
    extraFieldInput: {
      backgroundColor: colors.GRAY[100],
      borderRadius: 6,
      padding: 10,
      fontSize: 14,
    },
    extraFieldInputWrapper: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colors.GRAY[100],
      borderRadius: 6,
      padding: 10,
    },
    extraFieldInputText: {
      fontSize: 14,
      color: colors.BLACK,
      flex: 1,
    },
    extraFieldPlaceholder: {
      color: colors.GRAY[400],
    },
    dateInput: {
      backgroundColor: colors.WHITE,
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      ...CARD_SHADOW,
    },
    dateInputText: {
      fontSize: 16,
      color: colors.BLACK,
    },
    backPhotoHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    hasBackTag: {
      flexDirection: 'row',
      alignItems: 'center',
      marginLeft: 10,
      backgroundColor: withOpacity(colors.SUCCESS, 0.12),
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 4,
    },
    hasBackText: {
      fontSize: 12,
      color: colors.SUCCESS,
      marginLeft: 4,
    },
    photoPreviewContainer: {
      position: 'relative',
      marginBottom: 12,
    },
    photoPreview: {
      width: '100%',
      height: 300,
      borderRadius: 8,
      resizeMode: 'cover',
    },
    removePhotoButton: {
      position: 'absolute',
      top: 8,
      right: 8,
      backgroundColor: colors.WHITE,
      borderRadius: 12,
      padding: 4,
    },
    backPhotoLabel: {
      position: 'absolute',
      bottom: 8,
      left: 8,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.SUCCESS,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 4,
    },
    backPhotoLabelText: {
      fontSize: 12,
      color: colors.WHITE,
      marginLeft: 4,
    },
    photoButtons: {
      flexDirection: 'row',
      justifyContent: 'space-around',
    },
    photoButton: {
      backgroundColor: colors.WHITE,
      borderRadius: 12,
      padding: 16,
      alignItems: 'center',
      width: '45%',
      ...CARD_SHADOW,
    },
    photoButtonText: {
      marginTop: 8,
      fontSize: 14,
      color: colors.PRIMARY,
      fontWeight: 'bold',
    },
    backPhotoButtons: {
      alignItems: 'center',
    },
    addBackPhotoButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: withOpacity(colors.PRIMARY, 0.06),
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.PRIMARY,
      borderStyle: 'dashed',
    },
    addBackPhotoText: {
      fontSize: 14,
      color: colors.PRIMARY,
      marginLeft: 8,
    },
    changeBackPhotoButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.WHITE,
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 8,
      ...CARD_SHADOW,
    },
    changeBackPhotoText: {
      fontSize: 14,
      color: colors.PRIMARY,
      marginLeft: 8,
    },
    saveButton: {
      flexDirection: 'row',
      backgroundColor: colors.PRIMARY,
      borderRadius: 12,
      padding: 16,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 20,
      ...CARD_SHADOW,
    },
    saveButtonText: {
      marginLeft: 8,
      fontSize: 18,
      fontWeight: 'bold',
      color: colors.WHITE,
    },
    cropOption: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    cropLabel: {
      fontSize: 16,
      color: colors.BLACK,
    },
    cropDimensions: {
      marginBottom: 24,
    },
    dimensionInputs: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 8,
    },
    dimensionInput: {
      flex: 1,
      backgroundColor: colors.GRAY[100],
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      textAlign: 'center',
      ...CARD_SHADOW,
    },
    dimensionSeparator: {
      marginHorizontal: 12,
      fontSize: 18,
      fontWeight: 'bold',
      color: colors.BLACK,
    },
    cropHint: {
      fontSize: 12,
      color: colors.GRAY[500],
      marginTop: 8,
    },
    confirmButton: {
      backgroundColor: colors.PRIMARY,
      borderRadius: 8,
      padding: 14,
      alignItems: 'center',
      ...CARD_SHADOW,
    },
    confirmButtonText: {
      fontSize: 16,
      fontWeight: 'bold',
      color: colors.WHITE,
    },
  })