import { StyleSheet } from 'react-native'
import { HEADER_PADDING_TOP } from '../constants/themes'
import { ResolvedColors } from '../types/theme'
import { withOpacity } from '../utils/colorUtils'

export const createUploadScreenStyles = (colors: ResolvedColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.SECONDARY,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      paddingTop: HEADER_PADDING_TOP,
      backgroundColor: colors.PRIMARY,
    },
    backButton: {
      padding: 8,
    },
    placeholder: {
      width: 40,
    },
    title: {
      fontSize: 20,
      fontWeight: 'bold',
      color: colors.WHITE,
    },
    form: {
      padding: 20,
    },
    formGroup: {
      marginBottom: 20,
    },
    label: {
      fontSize: 16,
      fontWeight: 'bold',
      color: colors.BLACK,
      marginBottom: 8,
    },
    input: {
      backgroundColor: colors.WHITE,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.BORDER,
      padding: 12,
      fontSize: 16,
    },
    idolNameContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    idolNameInput: {
      flex: 1,
      backgroundColor: colors.WHITE,
      borderTopLeftRadius: 6,
      borderBottomLeftRadius: 6,
      borderWidth: 1,
      borderColor: colors.BORDER,
      padding: 12,
      fontSize: 16,
    },
    selectIdolButton: {
      backgroundColor: colors.WHITE,
      borderTopRightRadius: 6,
      borderBottomRightRadius: 6,
      borderWidth: 1,
      borderLeftWidth: 0,
      borderColor: colors.BORDER,
      padding: 12,
    },
    selectIdolHintButton: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 8,
      padding: 8,
    },
    selectIdolHintText: {
      marginLeft: 6,
      fontSize: 14,
      color: colors.PRIMARY,
    },
    dateInput: {
      backgroundColor: colors.WHITE,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.BORDER,
      padding: 12,
      fontSize: 16,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    dateInputText: {
      fontSize: 16,
      color: colors.BLACK,
    },
    photoButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    photoButton: {
      backgroundColor: colors.WHITE,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.BORDER,
      padding: 16,
      alignItems: 'center',
      width: '31%',
    },
    photoButtonText: {
      marginTop: 6,
      fontSize: 13,
      color: colors.PRIMARY,
      fontWeight: 'bold',
    },
    photoListHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    photoListSummary: {
      flexDirection: 'row',
    },
    totalCount: {
      fontSize: 14,
      color: colors.GRAY[600],
    },
    totalPrice: {
      fontSize: 14,
      color: colors.PRIMARY,
      fontWeight: 'bold',
    },
    mergeToggleContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: withOpacity(colors.PRIMARY, 0.06),
      borderRadius: 6,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginBottom: 12,
    },
    mergeToggleLabel: {
      fontSize: 14,
      color: colors.BLACK,
      fontWeight: '500',
    },
    photoItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.WHITE,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.BORDER,
      padding: 10,
      marginBottom: 10,
    },
    photoThumbnailContainer: {
      position: 'relative',
    },
    photoThumbnail: {
      width: 60,
      height: 60,
      borderRadius: 4,
    },
    backPhotoBadge: {
      position: 'absolute',
      bottom: -4,
      right: -4,
      backgroundColor: colors.SUCCESS,
      borderRadius: 8,
      padding: 2,
    },
    photoInfo: {
      flex: 1,
      marginLeft: 12,
    },
    photoInfoHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 4,
    },
    photoIndex: {
      fontSize: 14,
      color: colors.BLACK,
      marginRight: 8,
    },
    backPhotoTag: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: withOpacity(colors.SUCCESS, 0.12),
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
    },
    backPhotoTagText: {
      fontSize: 11,
      color: colors.SUCCESS,
      marginLeft: 2,
    },
    countInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 6,
    },
    countLabel: {
      fontSize: 14,
      color: colors.GRAY[600],
      marginRight: 8,
    },
    countInput: {
      backgroundColor: colors.GRAY[100],
      borderRadius: 6,
      padding: 6,
      width: 60,
      fontSize: 14,
      textAlign: 'center',
    },
    noteInputContainer: {
      marginBottom: 6,
    },
    noteInput: {
      backgroundColor: colors.GRAY[100],
      borderRadius: 6,
      padding: 8,
      fontSize: 14,
      minHeight: 40,
      textAlignVertical: 'top',
    },
    extraFieldsContainer: {
      marginTop: 8,
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: colors.GRAY[200],
    },
    extraFieldRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 6,
    },
    extraFieldHalf: {
      flex: 1,
    },
    extraFieldFull: {
      marginBottom: 6,
    },
    extraFieldLabel: {
      fontSize: 13,
      color: colors.GRAY[600],
      marginBottom: 4,
    },
    extraFieldInput: {
      backgroundColor: colors.GRAY[100],
      borderRadius: 6,
      padding: 8,
      fontSize: 14,
    },
    extraFieldInputWrapper: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colors.GRAY[100],
      borderRadius: 6,
      padding: 8,
    },
    extraFieldInputText: {
      fontSize: 14,
      color: colors.BLACK,
      flex: 1,
    },
    extraFieldPlaceholder: {
      color: colors.GRAY[400],
    },
    photoActions: {
      flexDirection: 'row',
    },
    addBackPhotoButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 4,
      paddingHorizontal: 8,
      backgroundColor: withOpacity(colors.PRIMARY, 0.06),
      borderRadius: 4,
    },
    addBackPhotoText: {
      fontSize: 12,
      color: colors.PRIMARY,
      marginLeft: 4,
    },
    removeBackPhotoButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 4,
      paddingHorizontal: 8,
      backgroundColor: withOpacity(colors.ERROR, 0.06),
      borderRadius: 4,
    },
    removeBackPhotoText: {
      fontSize: 12,
      color: colors.ERROR,
      marginLeft: 4,
    },
    removePhotoButton: {
      padding: 4,
    },
    saveButton: {
      flexDirection: 'row',
      backgroundColor: colors.PRIMARY,
      borderRadius: 8,
      padding: 16,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 20,
    },
    saveButtonText: {
      marginLeft: 8,
      fontSize: 18,
      fontWeight: 'bold',
      color: colors.WHITE,
    },
    cropOption: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    cropLabel: {
      fontSize: 16,
      color: colors.BLACK,
    },
    cropDimensions: {
      marginBottom: 24,
    },
    dimensionInputs: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 8,
    },
    dimensionInput: {
      flex: 1,
      backgroundColor: colors.GRAY[100],
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.BORDER,
      padding: 12,
      fontSize: 16,
      textAlign: 'center',
    },
    dimensionSeparator: {
      marginHorizontal: 12,
      fontSize: 18,
      fontWeight: 'bold',
      color: colors.BLACK,
    },
    cropHint: {
      fontSize: 12,
      color: colors.GRAY[500],
      marginTop: 8,
    },
    confirmButton: {
      backgroundColor: colors.PRIMARY,
      borderRadius: 8,
      padding: 14,
      alignItems: 'center',
    },
    confirmButtonText: {
      fontSize: 16,
      fontWeight: 'bold',
      color: colors.WHITE,
    },
    priceSelectButton: {
      padding: 6,
      marginLeft: 4,
    },
    globalFieldsRow: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 8,
    },
    globalFieldHalf: {
      flex: 1,
    },
    globalFieldFull: {
      flex: 1,
    },
    priceOption: {
      backgroundColor: colors.GRAY[100],
      borderRadius: 6,
      padding: 14,
      marginBottom: 10,
      alignItems: 'center',
    },
    priceOptionText: {
      fontSize: 18,
      fontWeight: 'bold',
      color: colors.PRIMARY,
    },
    priceOptionManual: {
      fontSize: 14,
      color: colors.GRAY[600],
      fontWeight: 'normal',
    },
  })
